//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Login
    {
        public int ID { get; set; }

        [DisplayName("User Name")]
        [Required(ErrorMessage = "* Username is Required ")]
        public string Username { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "* password is Required ")]
        public string Passwd { get; set; }

        
        public string Err { get; set; }
    }
}
